import numpy as np
import altair as alt


def highlight_min(s):
    if s.dtype == np.object:
        is_min = [False for _ in range(s.shape[0])]
    else:
        is_min = s == s.min()

    return ["background: powderblue" if cell else "" for cell in is_min]


FONT = "Averta"
TITLE_FONT = "Averta"
FONTSIZE_TITLE = 16
FONTSIZE_SUBTITLE = 13
FONTSIZE_NORMAL = 13

NESTA_COLOURS = [
    "lightgrey",
    "#0000FF",
    "#18A48C",
    "#9A1BBE",
    "#EB003B",
    "#FF6E47",
    "#646363",
    "#0F294A",
    "#97D9E3",
    "#A59BEE",
    "#F6A4B7",
    "#FDB633",
    "#D2C9C0",
    "#FFFFFF",
    "#000000",
]

LSOA_IN_EXTREME_10 = [
    "W01000028",
    "W01000041",
    "W01000048",
    "W01000050",
    "W01000051",
    "W01000057",
    "W01000086",
    "W01000096",
    "W01000112",
    "W01000138",
    "W01000167",
    "W01000176",
    "W01000189",
    "W01000194",
    "W01000228",
    "W01000328",
    "W01000360",
    "W01000362",
    "W01000379",
    "W01000381",
    "W01000409",
    "W01000427",
    "W01000510",
    "W01000531",
    "W01000537",
    "W01000539",
    "W01000541",
    "W01000542",
    "W01000550",
    "W01000589",
    "W01000603",
    "W01000626",
    "W01000646",
    "W01000685",
    "W01000725",
    "W01000744",
    "W01000746",
    "W01000809",
    "W01000830",
    "W01000834",
    "W01000851",
    "W01000856",
    "W01000867",
    "W01000886",
    "W01000898",
    "W01000901",
    "W01000914",
    "W01000920",
    "W01000921",
    "W01000922",
    "W01000924",
    "W01000930",
    "W01000942",
    "W01000950",
    "W01000958",
    "W01000965",
    "W01000967",
    "W01000971",
    "W01000976",
    "W01000993",
    "W01001004",
    "W01001022",
    "W01001045",
    "W01001046",
    "W01001071",
    "W01001183",
    "W01001201",
    "W01001205",
    "W01001206",
    "W01001211",
    "W01001215",
    "W01001229",
    "W01001274",
    "W01001275",
    "W01001276",
    "W01001287",
    "W01001307",
    "W01001329",
    "W01001386",
    "W01001410",
    "W01001451",
    "W01001457",
    "W01001462",
    "W01001483",
    "W01001487",
    "W01001506",
    "W01001519",
    "W01001605",
    "W01001645",
    "W01001693",
    "W01001695",
    "W01001696",
    "W01001697",
    "W01001718",
    "W01001721",
    "W01001837",
    "W01001866",
    "W01001922",
    "W01001924",
    "W01001939",
    "W01001943",
    "W01001945",
    "W01001952",
]


def nestafont():
    """Define Nesta fonts"""
    return {
        "config": {
            "title": {"font": TITLE_FONT, "anchor": "start"},
            "axis": {"labelFont": FONT, "titleFont": FONT},
            "header": {"labelFont": FONT, "titleFont": FONT},
            "legend": {"labelFont": FONT, "titleFont": FONT},
            "range": {
                "category": NESTA_COLOURS,
                "ordinal": {
                    "scheme": NESTA_COLOURS
                },  # this will interpolate the colors
            },
        }
    }


COLUMN_NAME_MAPPINGS = {
    "LSOA code": "lsoa_code",
    "LSOA name (1)": "lsoa_name_1",
    "LSOA name (2)": "lsoa_name_2",
    "MSOA code": "middle_layer_super_output_area_msoa_code",
    "MSOA name": "middle_layer_super_output_area_msoa_name",
    "LA code": "local_authority_la_code",
    "LA name": "local_authority_la_name",
    "Rural-Urban": "rural_urban",
    "Rural-Urban detailed classification": "rural_urban_classification",
    "Built-up area code": "built_up_area_bua_code",
    "Build-up area name": "built_up_area_bua_name",
    "Economic region code": "economic_region_economic_action_plan_area_eap_code",
    "Number of children 0-5 (2020)": "number_of_children_0_to_5_2020",
    "Number of births to mothers aged 24 and under (2020)": "number_of_births_2020_to_mothers_24_and_under_years",
    "Number of births to mothers aged 25-34 (2020)": "number_of_births_2020_to_mothers_25_to_34_years",
    "Number of births to mothers aged 35 and over (2020)": "number_of_births_2020_to_mothers_35_and_over_years",
    "Total number of births (2020)": "total_number_of_births_2020",
    "Population - all ages (2020)": "population_2020_all_ages",
    "Birth rate per 1000 (2020)": "birth_rate_per_1000_2020",
    "Number of births to mothers aged 24 and under (2019)": "number_of_births_2019_to_mothers_24_and_under_years",
    "Number of births to mothers aged 25-34 (2019)": "number_of_births_2019_to_mothers_25_to_34_years",
    "Number of births to mothers aged 35 and over (2019)": "number_of_births_2019_to_mothers_35_and_over_years",
    "Total number of births (2019)": "total_number_of_births_2019",
    "Population - all ages (2019)": "population_2019_all_ages",
    "Birth rate per 1000 (2019)": "birth_rate_per_1000_2019",
    "Number of births to mothers aged 24 and under (2018)": "number_of_births_2018_to_mothers_24_and_under_years",
    "Number of births to mothers aged 25-34 (2018)": "number_of_births_2018_to_mothers_25_to_34_years",
    "Number of births to mothers aged 35 and over (2018)": "number_of_births_2018_to_mothers_35_and_over_years",
    "Total number of births (2018)": "total_number_of_births_2018",
    "Population - all ages (2018)": "population_2018_all_ages",
    "Birth rate per 1000 (2018)": "birth_rate_per_1000_2018",
    "Number of births to mothers aged 24 and under (2017)": "number_of_births_2017_to_mothers_24_and_under_years",
    "Number of births to mothers aged 25-34 (2017)": "number_of_births_2017_to_mothers_25_to_34_years",
    "Number of births to mothers aged 35 and over (2017)": "number_of_births_2017_to_mothers_35_and_over_years",
    "Total number of births (2017)": "total_number_of_births_2017",
    "Population - all ages (2017)": "population_2017_all_ages",
    "Birth rate per 1000 (2017)": "birth_rate_per_1000_2017",
    "WIMD decile": "wimd_decile",
    "Number of children living in income deprivation aged 0-4 years old (2019)": "wimd_income_deprivation_count_0_to_4",
    "WIMD income domain deciles": "wimd_income_domain_deciles",
    "WIMD income domain - percentage of people in income deprivation": "wimd_income_domain_people_in_income_deprivation_percentage",
    "WIMD employment domain deciles": "wimd_employment_domain_deciles",
    "WIMD employment domain - percentage of people in employment deprivation": "wimd_employment_domain_working_age_people_in_employment_deprivation_percentage",
    "WIMD health domain deciles": "wimd_health_domain_deciles",
    "WIMD health domain - GP recorded chronic condition rate (per 100)": "wimd_health_domain_gp_recorded_chronic_condition_rate_per_100",
    "WIMD health domain - limiting long-term illness rate (per 100)": "wimd_health_domain_limiting_long_term_illness_rate_per_100",
    "WIMD health domain - premature death rate (per 100,000)": "wimd_health_domain_premature_death_rate_per_100,000",
    "WIMD health domain - GP recorded mental health condition rate (per 100)": "wimd_health_domain_gp_recorded_mental_health_condition_rate_per_100",
    "WIMD health domain - cancer incidence rate (per 100,000)": "wimd_health_domain_cancer_incidence_rate_per_100,000",
    "WIMD health domain - low birth weight, live single births less than 2.5 kg (percentage)": "wimd_health_domain_low_birth_weight_live_single_births_less_than_2_point_5kg_percentage",
    "WIMD health domain - percentage of children aged 4-5 who are obese": "wimd_health_domain_children_aged_4_to_5_who_are_obese_percentage",
    "WIMD education domain deciles": "wimd_education_domain_deciles",
    "WIMD education domain - foundation phase average point score": "wimd_education_domain_foundation_phase_average_point_score",
    "WIMD education domain - key stage 2 average point score": "wimd_education_domain_key_stage_2_average_point_score",
    "WIMD education domain - key stage 4 average point score": "wimd_education_domain_key_stage_4_average_point_score",
    "WIMD education domain - repeat absenteeism percentage": "wimd_education_domain_repeat_absenteeism_percentage",
    "WIMD education domain - percentage of key stage 4 leavers entering higher education": "wimd_education_domain_key_stage_4_leavers_entering_higher_education_percentage",
    "WIMD education domain - percentage of adults aged 25-64 with no qualifications": "wimd_education_domain_adults_aged_25_to_64_with_no_qualifications_percentage",
    "WIMD access to services domain deciles": "wimd_access_to_services_domain_deciles",
    "WIMD access to services domain - percentage unavailability of broadband at 30 mb/s": "wimd_access_to_services_domain_percentage_unavailability_of_broadband_at_30mb_s",
    "WIMD access to services domain - average public return traveltime to a pharmacy (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_pharmacy_mins",
    "WIMD access to services domain - average public return traveltime to a food shop (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_food_shop_mins",
    "WIMD access to services domain - average public return traveltime to a GP surgery (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_gp_surgery_mins",
    "WIMD access to services domain - average public return traveltime to a post office (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_post_office_mins",
    "WIMD access to services domain - average public return traveltime to a primary school (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_primary_school_mins",
    "WIMD access to services domain - average public return traveltime to a public library (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_public_library_mins",
    "WIMD access to services domain - average public return traveltime to a sports facility (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_sports_facility_mins",
    "WIMD access to services domain - average public return traveltime to a secondary school (mins)": "wimd_access_to_services_domain_average_public_return_travel_time_to_a_secondary_school_mins",
    "WIMD access to services domain - average private return traveltime to a pharmacy (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_pharmacy_mins",
    "WIMD access to services domain - average private return traveltime to a food shop (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_food_shop_mins",
    "WIMD access to services domain - average private return traveltime to a GP surgery (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_gp_surgery_mins",
    "WIMD access to services domain - average private return traveltime to a post office (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_post_office_mins",
    "WIMD access to services domain - average private return traveltime to a primary school (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_primary_school_mins",
    "WIMD access to services domain - average private return traveltime to a public library (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_public_library_mins",
    "WIMD access to services domain - average private return traveltime to a sports facility (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_sports_facility_mins",
    "WIMD access to services domain - average private return traveltime to a secondary school (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_secondary_school_mins",
    "WIMD access to services domain - average private return traveltime to a petrol station (mins)": "wimd_access_to_services_domain_average_private_return_travel_time_to_a_petrol_station_mins",
    "WIMD housing domain deciles": "wimd_housing_domain_deciles",
    "WIMD housing domain - percentage of people in overcrowded households": "wimd_housing_domain_people_in_overcrowded_households_percentage",
    "WIMD housing domain - percentage likelihood of poor quality housing": "wimd_housing_domain_likelihood_of_poor_quality_housing_percentage",
    "WIMD housing domain - percentage likelihood of housing containing serious hazards": "wimd_housing_domain_likelihood_of_housing_containing_serious_hazards_percentage",
    "WIMD housing domain - percentage likelihood of housing being in disrepair": "wimd_housing_domain_likelihood_of_housing_being_in_disrepair_percentage",
    "WIMD physical environment domain deciles": "wimd_physical_environment_domain_deciles",
    "WIMD physical environment domain - population weighted average concentration value for no2": "wimd_physical_environment_domain_population_weighted_average_concentration_value_for_no2",
    "WIMD physical environment domain - population weighted average concentration value for particulates <10μm": "wimd_physical_environment_domain_population_weighted_average_concentration_value_for_particulates__less_than_10_microm",
    "WIMD physical environment domain - population weighted average concentration value for particulates <2.5μm": "wimd_physical_environment_domain_population_weighted_average_concentration_value_for_particulates_less_than_2_point_5_micro_m",
    "WIMD physical environment domain - households at risk of flooding score": "wimd_physical_environment_domain_households_at_risk_of_flooding_score",
    "WIMD physical environment domain - proximity to accessible natural green space score (percentage of households)": "wimd_physical_environment_domain_proximity_to_accessible_natural_green_space_score_percentage_of_households",
    "WIMD physical environment domain - ambient green space score": "wimd_physical_environment_domain_ambient_green_space_score",
    "WIMD community safety domain deciles": "wimd_community_safety_domain_deciles",
    "WIMD community safety domain - police recorded criminal damage (rate per 100)": "wimd_community_safety_domain_police_recorded_criminal_damage_rate_per_100",
    "WIMD community safety domain - police recorded violent crime (rate per 100)": "wimd_community_safety_domain_police_recorded_violent_crime_rate_per_100",
    "WIMD community safety domain - police recorded anit-social behaviour (rate per 100)": "wimd_community_safety_domain_anti_social_behaviour_rate_per_100",
    "WIMD community safety domain - police recorded burglary (rate per 100)": "wimd_community_safety_domain_police_recorded_burglary_rate_per_100",
    "WIMD community safety domain - police recorded theft (rate per 100)": "wimd_community_safety_domain_police_recorded_theft_rate_per_100",
    "WIMD community safety domain - fire incidences (rate per 100)": "wimd_community_safety_domain_fire_incidences_rate_per_100",
    "Mean foundation phase score": "mean_fpp_score",
    "Mean foundation phase score (rounded)": "mean_fpp_score_rounded",
    "Foundation phase (mean difference)": "fpp_mean_difference",
    "Foundation phase performance": "fpp_performance",
    "Lower Layer Super Output Area (LSOA) Code": "Lower Layer Super Output Area (LSOA) Code",
    "LSOA Name": "LSOA Name",
    "Local Authority (LA) Code": "Local Authority (LA) Code",
    "Local Authority (LA) Name": "Local Authority (LA) Name",
    "Middle Layer Super Output Area (MSOA) Code": "Middle Layer Super Output Area (MSOA) Code",
    "Middle Layer Super Output Area (MSOA) Name": "Middle Layer Super Output Area (MSOA) Name",
    "Local Health Board (LHB) Code": "Local Health Board (LHB) Code",
    "Local Health Board (LHB) Name": "Local Health Board (LHB) Name",
    "Rural/ Urban Settlement Classification (RU) Code": "Rural/ Urban Settlement Classification (RU) Code",
    "Rural/ Urban Settlement Classification (RU) Name": "Rural/ Urban Settlement Classification (RU) Name",
    "Built Up Area (BUA) Code": "Built Up Area (BUA) Code",
    "Built Up Area (BUA) Name": "Built Up Area (BUA) Name",
    "Economic Region/ Economic Action Plan Area (EAP) Code": "Economic Region/ Economic Action Plan Area (EAP) Code",
    "Economic Region/ Economic Action Plan Area (EAP) Name": "Economic Region/ Economic Action Plan Area (EAP) Name",
    "Constituency Area (CA) Code": "Constituency Area (CA) Code",
    "Constituency Area (CA) Name": "Constituency Area (CA) Name",
    "City Region (CR) Code": "City Region (CR) Code",
    "City Region (CR) Name": "City Region (CR) Name",
    "Communities First (CF) Code": "Communities First (CF) Code",
    "Communities First (CF) Name": "Communities First (CF) Name",
    "Primary Care Cluster Code": "Primary Care Cluster Code",
    "Primary Care Cluster Name": "Primary Care Cluster Name",
}
